#!/bin/sh
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
    echo "Running emulator..."
    exec /rie node /function/app/node_modules/aws-lambda-ric/bin/index.js $@
else
    exec node /function/app/node_modules/aws-lambda-ric/bin/index.js $@
fi     